### ISSUE TITLE
Allow multiple `authorize_actions_for`

### ISSUE THREAD

**Issue by evansagge** [nathanl/authority#82]
I'm thinking of doing this in my controller:

```
class UsersController < ApplicationController
  authorize_actions_for User, only: %w(index create)
  authorize_actions_for :user, except: %w(index create)

  ...

  protected

  def user
    @user ||= User.find(params[:id])
  end
end
```

Unfortunately, it looks like invoking `authorize_actions_for` a second time completely overrides the `authority_resource` to `:user`.

Right now, to get away with this, this is how I get away with this issue:

```
class UsersController < ApplicationController
  authorize_actions_for :authority_resource

  ...

  protected

  def authority_resource
   params[:action].in?(%w(index create)) ? User : user
  end

  def user
    @user ||= User.find(params[:id])
  end
end
```

**Comment by sibsfinx** [comment]
+1 :+1: 
Currently using this
```
before_filter :authorize_organization
authorize_actions_for :load_task, except: [:index, :new, :create]

def authorize_organization
  # redirect with alert if not allowed
end
```
But I think this one would be better
```
authorize_actions_for :parent_organization, all_actions: :read
authorize_actions_for :load_task, except: [:index, :new, :create]
```

**Comment by christhekeele** [comment]
I'm trying to think through how this would work, and I'm leaning towards keeping the declaration the same: simple, and non-ambiguous.

Right now `authorize_actions_for` creates a single controller filter. Supporting multiple declarations would either mean:

- Finding a way to sanely combine multiple `:only`, `:except`, and `:all_actions` constraints properly on a single filter, or
- Creating a new filter for each usage of the declaration and tracking multiple `authority_resources`.

The latter is the only viable option, but I think both of your usecases can be accommodated by the existing feature set.

@evansagge in many of my Authority-powered applications, I end up doing something much like that:

```ruby
class UsersController < ApplicationController
  authorize_actions_for :resource
protected
  def resource
    @resource ||= User.find(params[:id]) rescue User
  end
end
```

I do this often enough I have a standard helper for generating the common case, and it's easy to override and extend for more complicated ones. This keeps my 'what is the resource' logic in a single place rather than spreading it thin across multiple `authorize_actions_for` declarations.

@sibsfinx, you may want to check out how to [handle failed authorization violations](https://github.com/nathanl/authority#security-violations--logging). By defining an `authority_forbidden` method on your controller or any of it's superclasses you can customize how failed checks behave. The [default implementation](https://github.com/nathanl/authority/blob/master/lib/authority/controller.rb#L126-L129) is to render a 403 error but it can be anything you like, including a redirect.

That should keep your authorization logic separate from your failed authorization logic. I may be misunderstanding what you want to do with multiple actions, though–is this what you were looking for?

**Comment by christhekeele** [comment]
Hey guys! (@evansagge, @sibsfinx)

I'm trying to triage issues so I can focus on the next planned release of Authority.

While my comments on both your approaches still ought to work in theory, a new major release gives me the opportunity to address the general desire to run multiple authorizers on different resources per request.

I'm closing this and will be opening up a new issue for it if it seems in scope. Feel free to weigh in on it when it appears, or jump in sooner in our [chat room](https://gitter.im/nathanl/authority).

Thanks for contributing your use-cases, it really helps me get an idea of where Authority ought to go next. :smile:

**Comment by nathanl** [comment]
> Creating a new filter for each usage of the declaration and tracking multiple authority_resource

@christhekeele Just got pointed back to this issue and haven't dug back into the code, but I wonder if instead of tracking multiple resources we could just let the user pass a proc to look up whatever they want?
